### ISSUE TITLE
Provide more outputs from the cellranger output

### ISSUE THREAD

**Issue by cnk113** [LieberInstitute/HumanPilot#4]
Hello,

I was wondering if it was possible to also upload aligned_fiducials.jpg, scalefactors_json.json, and tissue_positions_list.csv from the spatial output in cellranger output?

Thanks,
Chang

**Comment by lcolladotor** [comment]
Hi,

Sorry for missing this issue. The full raw data is available from Globus as noted at https://github.com/LieberInstitute/HumanPilot#raw-data.

Best,
Leo

**Comment by cmzuo11** [comment]
> Hi,
> 
> Sorry for missing this issue. The full raw data is available from Globus as noted at https://github.com/LieberInstitute/HumanPilot#raw-data.
> 
> Best,
> Leo

Dear Leo,

I have tried to download raw data from your provided link, but I can't have access to this data. Could you please share me with the data by AWS?

Thanks so much for your kind help!

Best,
chunman

**Comment by lcolladotor** [comment]
Hi Chunman,

The high performance computing (HPC) system we use, JHPCE, was down last week and the JHPCE admins had to fix a few issues related to Globus. That's why it likely wasn't working when you tried accessing the data 7 hours ago. Can you try again now? JHPCE admins notified me of this fix 5 minutes ago.

Thanks!

Best,
Leo

**Comment by lcolladotor** [comment]
If Globus works for you, then we can close the issue. Thanks!

**Comment by cmzuo11** [comment]
> If Globus works for you, then we can close the issue. Thanks!

Hi Leo,

Yes, it works. Please close it.

Thanks so much for your quick reply.

Best,
chunman
